---
title: "tip00_basic"
author: "ne_choi"
date: '2020 10 11 '
output:
  html_document:
   toc: true
   toc_float:
     collapsed: false
     smooth_scroll: true
   theme: united
   highlight: textmate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. github
 

# 2. R
## 1. R Markdown 형식
```
title: "tip00_basic" #문서 제목 지정
author: "ne_choi" #저자
date: '2020 10 11 ' #발행 날짜
output:
  html_document: #html 문서 생성
   toc: true #목차 추가
   toc_float: #스크롤에 맞춰 목차 이동
   collapsed: false #목차 최상위 수준만 기본 노출
     smooth_scroll: true #목차 선택 시 화면 부드럽게 이동
   theme: united #기본 스타일 지정 테마
   highlight: textmate #구문 하이라이트
```

## 2. 엑셀 데이터 합치기
```{r}
library(dplyr)
library(readxl)

files <- list.files(path = "엑셀 있는 폴더 경로", pattern = "*.xlsx", full.names = T)  
products <- sapply(files, read_excel, simplify = FALSE) %>% 
  bind_rows(.id = "id")
```

## 3. ggplot2 시각화
# 시각화 테마를 위한 bbplot 패키지 설치 
```
if(!require(pacman))install.packages("pacman")
```
```{r}
pacman::p_load('dplyr', 'tidyr', 'gapminder',
               'ggplot2',  'ggalt',
               'forcats', 'R.utils', 'png', 
               'grid', 'ggpubr', 'scales',
               'bbplot')
```


# 3. python

